language: node_js
node_js:
  - '12'
cache:
  - node_modules
install:
  - yarn add coveralls
  - yarn install
script:
  - yarn run lint
  - yarn run coverage
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
